### ISSUE TITLE
[BUG] `\date` not visible in `\titlepage{}`

### ISSUE THREAD

**Issue by earnestma** [kai-tub/latex-beamer-pure-minimalistic#76]
When `\date{\today}` or similar is set and then `\titlepage` is called, the date does not appear.

This is also present on the demos in this repository:

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/51169564/200342482-36cdf1f0-6da3-45c7-8cee-9b3b9818a6ef.png">

**Comment by earnestma** [comment]
Here's a preliminary fix, but I have not tested this extensively.

(**EDIT**: the date font is smaller, so i think it looks better before subtitle and after author/ institution info)

```diff
# earne@blahaj [/usr/local/texlive/2022/texmf-dist/tex/latex/beamertheme-pure-minimalistic]
# ❯ diff ~/ghq/github.com/kai-tub/latex-beamer-pure-minimalistic/beamerinnerthemepureminimalistic.sty beamerinnerthemepureminimalistic.sty
22c22
< \ProvidesPackage{beamerinnerthemepureminimalistic}[v2.0.1]
---
> \ProvidesPackage{beamerinnerthemepureminimalistic}[v2.0.0]
103a104,107
>         \ifx\insertdate\@empty%
>           \else%
>           {\usebeamerfont{date}\insertdate $\quad$}%
>         \fi%
```

**Comment by kai-tub** [comment]
Hey, first of all, thank you for starring the repository and bringing the number of stars to 100 :partying_face: and thank you for creating the issue!
You are right. I prefer to have no date information on my title page and never thought about supporting it (and never tested it, as you can see :D )

Your patch looks good and I would be happy to take a PR if you like, otherwise, I would just copy the changes.

Just one thing, I would like to discuss.
I think that the subtitle _should_ have a larger font size to differentiate it from the 'metadata' but I personally would enforce it to the first line and push the other lines below that. Something like this:

![image](https://user-images.githubusercontent.com/46302524/200391135-ca83749e-ded1-40fc-bddf-0da7f8b106d3.png)

(Although I would further tune the spacing to look more natural)

What are your thoughts?

**Comment by earnestma** [comment]
> Hey, first of all, thank you for starring the repository and bringing the number of stars to 100 🥳

Congratulations! 🎉

> Just one thing, I would like to discuss. I think that the subtitle _should_ have a larger font size to differentiate it from the 'metadata' but I personally would enforce it to the first line and push the other lines below that. Something like this:
> 
> (Although I would further tune the spacing to look more natural)
> 
> What are your thoughts?

I believe the subtitle's font is by default a bit larger than author/institute/date, so it definitely sounds good to have it on a separate line. I'll try to have a pull request within the next few days.
